### ISSUE TITLE
cannot create ARG_DB

### ISSUE THREAD

**Issue by YiweiZhu** [lgpdevtools/sraX#2]
it prints:
Use of uninitialized value $out_dir in concatenation (.) or string at PATH TO/sraX/sraXlib/Dir.pm line 10.
creating '/ARG_DB' failed

Should I obtain the root authority first?

**Comment by lgpdevtools** [comment]
Hello YiweiZhu,
Probably you are trying to run the tool inside a folder that requires root privileges. If not, just check the output given name.
