### ISSUE TITLE
conda install & permission issue on runs

### ISSUE THREAD

**Issue by ewissel** [lgpdevtools/sraX#3]
Hey sraX devs,

I'm trying to run this on a file `contigs.fasta` using the following commands:

```
 conda create –name sraX 
conda activate sraX 
sraX –v  ## indicates successful install
## now run on data
sraX -i sim_dat/fasta/ -o sraX_out/
```

I get the following error because I don't have permissions to write to the directory sraX is trying to write to:

```
> Use of uninitialized value $dir in -d at /home/ewissel/miniconda3/envs/sraX/bin/sraXlib/Functions.pm line 259.
> Use of uninitialized value $out_dir in concatenation (.) or string at /home/ewissel/miniconda3/envs/sraX/bin/sraXlib/Dir.pm line 10.
> mkdir: cannot create directory ‘/ARG_DB’: Permission denied
> Use of uninitialized value $out_dir in concatenation (.) or string at /home/ewissel/miniconda3/envs/sraX/bin/sraXlib/Dir.pm line 10.
> 
> [Error]: The '/ARG_DB' directory cannot be created. sraX execution is stopped and the resistome analysis is aborted now.
```

It's not clear to me if there is a flag for re-routing the `ARG_DB` to install to a location I have permissions to write to (it is entirely likely I missed this in the documentation?). Can you point me towards the flag for redirecting where this directory is written?

**Comment by lgpdevtools** [comment]
Hello Emiliy,
Thank you for your inquiry. The problem arises from the given name of the output directory. Actually, is the extra ending slash that is causing trouble when building the directory structure. You should just run:
sraX -i sim_dat/fasta/ -o sraX_out

**Comment by ewissel** [comment]
This fixed it, thanks!
