### ISSUE TITLE
sraX - no plots generated

### ISSUE THREAD

**Issue by gaworj** [lgpdevtools/sraX#4]
Hi,

First of all thank you very much for such amazing tool!
I have installed SraX using conda and plots are not generated.
After inspecting log files I have noticed that R packages are not installed so they were installed also via conda.
Unfortunately the problem persist.
Please have a look:

The creation of summary files finished at:	Time: 23:21 hs | Date: 2021-10-19

The creation of HTML files plus embedded summary plots started at:	Time: 23:21 hs | Date: 2021-10-19

Error in position_fill(vjust = 0.5) : unused argument (vjust = 0.5)
Calls: geom_text -> layer -> position_fill
Execution halted

	The creation of HTML files plus embedded summary plots took 0.80  wallclock secs

The creation of HTML files plus embedded summary plots finished at:	Time: 23:21 hs | Date: 2021-10-19

Any hints?

Bests,
Jan

**Comment by lgpdevtools** [comment]
Hi gaworj,

Thank you very much for your interest in using this tool. Regarding your bug, it seems to be related to some R package. Could you please tell me which version of ggplot2 have you installed via conda?

**Comment by gaworj** [comment]
Hi,

Thank you very much for your helpfulness.
Here is the terminal output after "conda list" in my srax env:

# packages in environment at /home/jang/anaconda3/envs/srax:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
_r-mutex                  1.0.1               anacondar_1    conda-forge
argtable2                 2.13              h14c3975_1001    conda-forge
blast                     2.10.1          pl526he19e7b1_3    bioconda
boost-cpp                 1.74.0               h312852a_4    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2021.10.8            ha878542_0    conda-forge
cairo                     1.16.0            h6cf1ce9_1008    conda-forge
clustalo                  1.2.4                h1b792b2_4    bioconda
curl                      7.71.1               he644dc0_3    conda-forge
diamond                   2.0.12               hdcc8f71_0    bioconda
entrez-direct             15.6                 he881be0_1    bioconda
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.13.1            hba837de_1005    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
freetype                  2.10.4               h0708190_1    conda-forge
fribidi                   1.0.10               h36c2ea0_0    conda-forge
gettext                   0.19.8.1          h73d1719_1008    conda-forge
graphite2                 1.3.13            h58526e2_1001    conda-forge
harfbuzz                  3.0.0                h83ec7ef_1    conda-forge
icu                       68.1                 h58526e2_0    conda-forge
jbig                      2.1               h7f98852_2003    conda-forge
jpeg                      9d                   h36c2ea0_0    conda-forge
krb5                      1.17.2               h926e7f8_0    conda-forge
lerc                      3.0                  h9c3ff4c_0    conda-forge
libcurl                   7.71.1               hcdd3856_3    conda-forge
libdeflate                1.8                  h7f98852_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libffi                    3.4.2                h9c3ff4c_4    conda-forge
libgcc                    7.2.0                h69d50b8_2    conda-forge
libgcc-ng                 11.2.0              h1d223b6_11    conda-forge
libglib                   2.70.0               h174f98d_0    conda-forge
libgomp                   11.2.0              h1d223b6_11    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libssh2                   1.10.0               ha56f1ee_2    conda-forge
libstdcxx-ng              11.2.0              he4da1e4_11    conda-forge
libtiff                   4.3.0                h6f004c6_2    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libwebp-base              1.2.1                h7f98852_0    conda-forge
libxcb                    1.13              h7f98852_1003    conda-forge
libxml2                   2.9.12               h72842e0_0    conda-forge
libzlib                   1.2.11            h36c2ea0_1013    conda-forge
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
mafft                     7.487                h779adbc_0    bioconda
muscle                    3.8.1551             h7d875b9_6    bioconda
ncurses                   6.2                  h58526e2_4    conda-forge
openssl                   1.1.1l               h7f98852_0    conda-forge
pango                     1.48.10              h54213e6_2    conda-forge
pcre                      8.45                 h9c3ff4c_0    conda-forge
perl                      5.26.2            h36c2ea0_1008    conda-forge
perl-apache-test          1.40                    pl526_1    bioconda
perl-app-cpanminus        1.7044                  pl526_1    bioconda
perl-archive-tar          2.32                    pl526_0    bioconda
perl-base                 2.23                    pl526_1    bioconda
perl-business-isbn        3.004                   pl526_0    bioconda
perl-business-isbn-data   20140910.003            pl526_0    bioconda
perl-carp                 1.38                    pl526_3    bioconda
perl-class-load           0.25                    pl526_0    bioconda
perl-class-load-xs        0.10            pl526h6bb024c_2    bioconda
perl-class-method-modifiers 2.12                    pl526_0    bioconda
perl-common-sense         3.74                    pl526_2    bioconda
perl-compress-raw-bzip2   2.087           pl526he1b5a44_0    bioconda
perl-compress-raw-zlib    2.087           pl526hc9558a2_0    bioconda
perl-constant             1.33                    pl526_1    bioconda
perl-data-dumper          2.173                   pl526_0    bioconda
perl-data-optlist         0.110                   pl526_2    bioconda
perl-devel-globaldestruction 0.14                    pl526_0    bioconda
perl-devel-overloadinfo   0.005                   pl526_0    bioconda
perl-devel-stacktrace     2.04                    pl526_0    bioconda
perl-digest-hmac          1.03                    pl526_3    bioconda
perl-digest-md5           2.55                    pl526_0    bioconda
perl-dist-checkconflicts  0.11                    pl526_2    bioconda
perl-encode               2.88                    pl526_1    bioconda
perl-encode-locale        1.05                    pl526_6    bioconda
perl-env-path             0.19                    pl526_2    bioconda
perl-eval-closure         0.14            pl526h6bb024c_4    bioconda
perl-exporter             5.72                    pl526_1    bioconda
perl-exporter-tiny        1.002001                pl526_0    bioconda
perl-extutils-makemaker   7.36                    pl526_1    bioconda
perl-file-listing         6.04                    pl526_1    bioconda
perl-file-path            2.16                    pl526_0    bioconda
perl-file-slurp           9999.27                 pl526_0    bioconda
perl-file-temp            0.2304                  pl526_2    bioconda
perl-file-which           1.23                    pl526_0    bioconda
perl-getopt-long          2.50                    pl526_1    bioconda
perl-html-parser          3.72            pl526h6bb024c_5    bioconda
perl-html-tagset          3.20                    pl526_3    bioconda
perl-http-cookies         6.04                    pl526_0    bioconda
perl-http-daemon          6.01                    pl526_1    bioconda
perl-http-date            6.02                    pl526_3    bioconda
perl-http-message         6.18                    pl526_0    bioconda
perl-http-negotiate       6.01                    pl526_3    bioconda
perl-io-compress          2.087           pl526he1b5a44_0    bioconda
perl-io-html              1.001                   pl526_2    bioconda
perl-io-socket-ssl        2.066                   pl526_0    bioconda
perl-io-zlib              1.10                    pl526_2    bioconda
perl-json                 4.02                    pl526_0    bioconda
perl-json-xs              2.34            pl526h6bb024c_3    bioconda
perl-libwww-perl          6.39                    pl526_0    bioconda
perl-list-moreutils       0.428                   pl526_1    bioconda
perl-list-moreutils-xs    0.428                   pl526_0    bioconda
perl-lwp-mediatypes       6.04                    pl526_0    bioconda
perl-lwp-protocol-https   6.07                    pl526_4    bioconda
perl-lwp-simple           6.15            pl526h470a237_4    bioconda
perl-mime-base64          3.15                    pl526_1    bioconda
perl-module-implementation 0.09                    pl526_2    bioconda
perl-module-runtime       0.016                   pl526_1    bioconda
perl-module-runtime-conflicts 0.003                   pl526_0    bioconda
perl-moo                  2.003004                pl526_0    bioconda
perl-moose                2.2011          pl526hf484d3e_1    bioconda
perl-mozilla-ca           20180117                pl526_1    bioconda
perl-mro-compat           0.13                    pl526_0    bioconda
perl-net-http             6.19                    pl526_0    bioconda
perl-net-ssleay           1.88            pl526h90d6eec_0    bioconda
perl-ntlm                 1.09                    pl526_4    bioconda
perl-package-deprecationmanager 0.17                    pl526_0    bioconda
perl-package-stash        0.38            pl526hf484d3e_1    bioconda
perl-package-stash-xs     0.28            pl526hf484d3e_1    bioconda
perl-parallel-forkmanager 2.02                    pl526_0    bioconda
perl-params-util          1.07            pl526h6bb024c_4    bioconda
perl-parent               0.236                   pl526_1    bioconda
perl-pathtools            3.75            pl526h14c3975_1    bioconda
perl-role-tiny            2.000008                pl526_0    bioconda
perl-scalar-list-utils    1.52            pl526h516909a_0    bioconda
perl-socket               2.027                   pl526_1    bioconda
perl-storable             3.15            pl526h14c3975_0    bioconda
perl-sub-exporter         0.987                   pl526_2    bioconda
perl-sub-exporter-progressive 0.001013                pl526_0    bioconda
perl-sub-identify         0.14            pl526h14c3975_0    bioconda
perl-sub-install          0.928                   pl526_2    bioconda
perl-sub-name             0.21                    pl526_1    bioconda
perl-sub-quote            2.006003                pl526_1    bioconda
perl-test-harness         3.42                    pl526_0    bioconda
perl-test-requiresinternet 0.05                    pl526_0    bioconda
perl-text-csv             2.00                    pl526_0    bioconda
perl-time-local           1.28                    pl526_1    bioconda
perl-try-tiny             0.30                    pl526_1    bioconda
perl-types-serialiser     1.0                     pl526_2    bioconda
perl-uri                  1.76                    pl526_0    bioconda
perl-www-robotrules       6.02                    pl526_3    bioconda
perl-xsloader             0.24                    pl526_0    bioconda
pixman                    0.40.0               h36c2ea0_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
r                         3.2.2                         0  
r-assertthat              0.1                   r3.2.2_1a  
r-base                    3.2.2                         0  
r-bh                      1.60.0_2               r3.2.2_0    bioconda
r-boot                    1.3_17                r3.2.2_0a  
r-class                   7.3_14                r3.2.2_0a  
r-cluster                 2.0.3                 r3.2.2_0a  
r-codetools               0.2_14                r3.2.2_0a  
r-colorspace              1.2_6                 r3.2.2_0a  
r-dbi                     0.3.1                 r3.2.2_2a  
r-dichromat               2.0_0                 r3.2.2_2a  
r-digest                  0.6.9                  r3.2.2_0    bioconda
r-dplyr                   0.4.3                 r3.2.2_0a  
r-foreign                 0.8_66                r3.2.2_0a  
r-ggplot2                 2.1.0                  r3.2.2_0    bioconda
r-gridextra               2.0.0                 r3.2.2_0a  
r-gtable                  0.1.2                 r3.2.2_2a  
r-kernsmooth              2.23_15               r3.2.2_0a  
r-labeling                0.3                   r3.2.2_1a  
r-lattice                 0.20_33               r3.2.2_0a  
r-lazyeval                0.1.10                r3.2.2_2a  
r-magrittr                1.5                    r3.2.2_0    bioconda
r-mass                    7.3_45                r3.2.2_0a  
r-matrix                  1.2_2                 r3.2.2_0a  
r-mgcv                    1.8_9                 r3.2.2_0a  
r-munsell                 0.4.2                 r3.2.2_1a  
r-nlme                    3.1_122               r3.2.2_0a  
r-nnet                    7.3_11                r3.2.2_0a  
r-plyr                    1.8.3                 r3.2.2_0a  
r-r6                      2.1.1                 r3.2.2_0a  
r-rcolorbrewer            1.1_2                 r3.2.2_2a  
r-rcpp                    0.12.2                r3.2.2_0a  
r-recommended             3.2.2                  r3.2.2_0  
r-reshape2                1.4.1                 r3.2.2_1a  
r-rpart                   4.1_10                r3.2.2_0a  
r-scales                  0.3.0                 r3.2.2_0a  
r-spatial                 7.3_11                r3.2.2_0a  
r-stringi                 1.0_1                 r3.2.2_0a  
r-stringr                 1.0.0                 r3.2.2_0a  
r-survival                2.38_3                r3.2.2_0a  
readline                  8.1                  h46c0cb4_0    conda-forge
srax                      1.5                           0    lgpdevtools
tk                        8.6.11               h27826a3_1    conda-forge
unzip                     6.0                  h7f98852_2    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.0.10               h7f98852_0    conda-forge
xorg-libsm                1.2.3             hd9c2040_1000    conda-forge
xorg-libx11               1.7.2                h7f98852_0    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h7f98852_1    conda-forge
xorg-libxrender           0.9.10            h7f98852_1003    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-xextproto            7.3.0             h7f98852_1002    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zlib                      1.2.11            h36c2ea0_1013    conda-forge
zstd                      1.5.0                ha95c52a_0    conda-forge

Bests,
Jan

**Comment by lgpdevtools** [comment]
Hi Jan,

It seems that your ggplot2 version (2.1.0) is quite old (Feb 2016). Please, firstly run the following commands for later running sraX:

conda create --name sraX
conda activate sraX
conda install srax
conda install r-ggplot2=3.2.1
conda install r-dplyr
conda install r-gridExtra
conda install r-stringr
conda install r-gplots

I've verified that the output was correctly produced, including -of course- the creation of plots.

Let me know then if some other issues arise.

**Comment by gaworj** [comment]
Hi,

Thank you for your very detailed installation instructions. Now it works like a charm.

**Comment by gaworj** [comment]
I have one additional question:
What are the exact recommendations for custom database?
Do I need to prepare fasta headers in specific way?
I would like to use sraX for virulence genes finding basing on VFDB database.
Already used VFDB formatted db for SRST2 but the sraX has problems with proper results visualization.

**Comment by lgpdevtools** [comment]
Indeed, the header is important for producing plots and also hyperlinks. Please, copy an example of the header that you've employed for creating your DB and I will tell you what can be improved for getting improved results.

**Comment by gaworj** [comment]
Thanks in advance!
There are two options:

a) VFDB database format:
>VFG000948(gb|NP_663908) (fbaB) fibronectin-bing protein SfbII [FBPs (VF0243)] [Streptococcus pyogenes MGAS315]

b)SRST2 compatibile header:
>104__fbaB__fbaB_VF0243__VFG000948 VFG000948(gb|NP_663908) (fbaB) fibronectin-bing protein SfbII [FBPs (VF0243)] [Streptococcus pyogenes MGAS315]

Each header starts of course with typical ">"

**Comment by lgpdevtools** [comment]
The headers should be written following this format:
>gene_name|accession_ID|gene_description|sequence_determination|gene_classification|organism name

For this example, your header should be formatted like this:
>fbaB|NP_663908|fibronectin-bing protein SfbII|protein_homolog|vf_gene_category|Streptococcus pyogenes
