### ISSUE TITLE
LWP::Protocol::https

### ISSUE THREAD

**Issue by kayobianco** [lgpdevtools/sraX#5]
Hi, 
the LWP::Protocol::https is installed, but i receive this error.

(base) arqueas@genome:~$ sraX -i /media/arqueas/UBUNTU-HD/Illumina/Plasmidoma/IWTP_ANA/sraX/fasta -o /media/arqueas/UBUNTU-HD/Illumina/Plasmidoma/IWTP_ANA/sraX/results -db ext
------------------------------------------------------------------
The 'sraX' analysis started at:	Time: 12:35 hs | Date: 2021-12-16
------------------------------------------------------------------

The compilation process of the local ARG DB started at:	Time: 12:35 hs | Date: 2021-12-16

	The downloading process of 'CARD' data started at:	Time: 12:35 hs | Date: 2021-12-16

	Failed to fetch data from 'CARD' AMR DB
	501 Protocol scheme 'https' is not supported (LWP::Protocol::https not installed)
	Some problems have impeded the correct downloading of 'CARD' data.
	In consequence, a previously pre-downloaded version of 'CARD' will be employed for the sraX analysis.

Can you help me?

**Comment by lgpdevtools** [comment]
Hi,
Thank you very much for your interest in this tool. I suggest installing conda (if you do not have it already) and run the following commands:

conda create --name sraX
conda activate sraX
conda install srax
conda install r-ggplot2=3.2.1
conda install r-dplyr
conda install r-gridExtra
conda install r-stringr
conda install r-gplots

Finally, from this activated conda environment, run sraX as you've described.

**Comment by kayobianco** [comment]
Thanks, that solved the problem.
