### ISSUE TITLE
SNP.pm

### ISSUE THREAD

**Issue by kayobianco** [lgpdevtools/sraX#9]
Hello everybody,

I'm trying to use the command "sraX -db ext -i "$input_dir" -o "$output_dir"" but several times the output is:
Use of uninitialized value in exists at /home/kayobianco/miniconda3/envs/sraX/bin/sraXlib/SNP.pm line 290.
Use of uninitialized value in hash element at /home/kayobianco/miniconda3/envs/sraX/bin/sraXlib/SNP.pm line 293.
Use of uninitialized value in exists at /home/kayobianco/miniconda3/envs/sraX/bin/sraXlib/SNP.pm line 290.
Use of uninitialized value in hash element at /home/kayobianco/miniconda3/envs/sraX/bin/sraXlib/SNP.pm line 293.
Use of uninitialized value in string eq at /home/kayobianco/miniconda3/envs/sraX/bin/sraXlib/SNP.pm line 304.
Use of uninitialized value in string eq at /home/kayobianco/miniconda3/envs/sraX/bin/sraXlib/SNP.pm line 304.
Use of uninitialized value in string eq at /home/kayobianco/miniconda3/envs/sraX/bin/sraXlib/SNP.pm line 316.
Use of uninitialized value in concatenation (.) or string at /home/kayobianco/miniconda3/envs/sraX/bin/sraXlib/SNP.pm line 317.
Use of uninitialized value in string eq at /home/kayobianco/miniconda3/envs/sraX/bin/sraXlib/SNP.pm line 304.
Use of uninitialized value in string eq at /home/kayobianco/miniconda3/envs/sraX/bin/sraXlib/SNP.pm line 304.
Use of uninitialized value in string eq at /home/kayobianco/miniconda3/envs/sraX/bin/sraXlib/SNP.pm line 304.
Use of uninitialized value in string eq at /home/kayobianco/miniconda3/envs/sraX/bin/sraXlib/SNP.pm line 316.
Use of uninitialized value in concatenation (.) or string at /home/kayobianco/miniconda3/envs/sraX/bin/sraXlib/SNP.pm line 317.
Use of uninitialized value in string eq at /home/kayobianco/miniconda3/envs/sraX/bin/sraXlib/SNP.pm line 304.
Use of uninitialized value in string eq at /home/kayobianco/miniconda3/envs/sraX/bin/sraXlib/SNP.pm line 304.
Use of uninitialized value in string eq at /home/kayobianco/miniconda3/envs/sraX/bin/sraXlib/SNP.pm line 304.
Use of uninitialized value in string eq at /home/kayobianco/miniconda3/envs/sraX/bin/sraXlib/SNP.pm line 316.
Use of uninitialized value in concatenation (.) or string at /home/kayobianco/miniconda3/envs/sraX/bin/sraXlib/SNP.pm line 317.
Use of uninitialized value in string eq at /home/kayobianco/miniconda3/envs/sraX/bin/sraXlib/SNP.pm line 304.
Use of uninitialized value in string eq at /home/kayobianco/miniconda3/envs/sraX/bin/sraXlib/SNP.pm line 304.
Use of uninitialized value in string eq at /home/kayobianco/miniconda3/envs/sraX/bin/sraXlib/SNP.pm line 304.
Use of uninitialized value in string eq at /home/kayobianco/miniconda3/envs/sraX/bin/sraXlib/SNP.pm line 316.
Use of uninitialized value in concatenation (.) or string at /home/kayobianco/miniconda3/envs/sraX/bin/sraXlib/SNP.pm line 317.
Use of uninitialized value in string eq at /home/kayobianco/miniconda3/envs/sraX/bin/sraXlib/SNP.pm line 304.
Use of uninitialized value in string eq at /home/kayobianco/miniconda3/envs/sraX/bin/sraXlib/SNP.pm line 304.
Use of uninitialized value in string eq at /home/kayobianco/miniconda3/envs/sraX/bin/sraXlib/SNP.pm line 304.
Use of uninitialized value in string eq at /home/kayobianco/miniconda3/envs/sraX/bin/sraXlib/SNP.pm line 316.
Use of uninitialized value in concatenation (.) or string at /home/kayobianco/miniconda3/envs/sraX/bin/sraXlib/SNP.pm line 317.
Use of uninitialized value in string eq at /home/kayobianco/miniconda3/envs/sraX/bin/sraXlib/SNP.pm line 304.
Use of uninitialized value in string eq at /home/kayobianco/miniconda3/envs/sraX/bin/sraXlib/SNP.pm line 304.
Use of uninitialized value in string eq at /home/kayobianco/miniconda3/envs/sraX/bin/sraXlib/SNP.pm line 304.
Use of uninitialized value in string eq at /home/kayobianco/miniconda3/envs/sraX/bin/sraXlib/SNP.pm line 316.
Use of uninitialized value in concatenation (.) or string at /home/kayobianco/miniconda3/envs/sraX/bin/sraXlib/SNP.pm line 317.
Use of uninitialized value in string eq at /home/kayobianco/miniconda3/envs/sraX/bin/sraXlib/SNP.pm line 304.
Use of uninitialized value in string eq at /home/kayobianco/miniconda3/envs/sraX/bin/sraXlib/SNP.pm line 304.
Use of uninitialized value in string eq at /home/kayobianco/miniconda3/envs/sraX/bin/sraXlib/SNP.pm line 304.
Use of uninitialized value in string eq at /home/kayobianco/miniconda3/envs/sraX/bin/sraXlib/SNP.pm line 316.
Use of uninitialized value in concatenation (.) or string at /home/kayobianco/miniconda3/envs/sraX/bin/sraXlib/SNP.pm line 317.
Use of uninitialized value in string eq at /home/kayobianco/miniconda3/envs/sraX/bin/sraXlib/SNP.pm line 304.
Use of uninitialized value in string eq at /home/kayobianco/miniconda3/envs/sraX/bin/sraXlib/SNP.pm line 304.
Use of uninitialized value in string eq at /home/kayobianco/miniconda3/envs/sraX/bin/sraXlib/SNP.pm line 304.
Use of uninitialized value in string eq at /home/kayobianco/miniconda3/envs/sraX/bin/sraXlib/SNP.pm line 316.
Use of uninitialized value in concatenation (.) or string at /home/kayobianco/miniconda3/envs/sraX/bin/sraXlib/SNP.pm line 317.

Can you help me?

**Comment by lgpdevtools** [comment]
Hi,

Thank you very much for your interest in using this tool. Please, send me a fasta file (with a sequence) that reproduce the warnings.

Best regards
